### ISSUE TITLE
Konsep nomor di tabel salah

### ISSUE THREAD

**Issue by reezhaa** [diskominfokepri/ssh#17]
Contoh : Penomoran data table di dashboard dimulai dari 1-10 di halaman 1, untuk halaman 2 kembali ke nomor 1 .. sedangkan penomoran data table di form daftar objek rekening/peralatan berurutan dari 1 hingga selesai ..

**Comment by yayabocil** [comment]
oke fix

**Comment by abdulionel** [comment]
fix
